"""
Quantum walks against classical random walks: distributions, limits and spread.

Produces, for Section 3.2 of the thesis,
  fig_walk_crw.pdf / .png   four panels (see below)
  tab_walk_crw.tex          spread, entropy and return probability at t = 100
  walk_vs_crw.json          every number quoted in the text

Everything is exact arithmetic on probability vectors or state vectors; nothing
is sampled. Only NumPy, SciPy (Bessel functions) and matplotlib are needed.

Panels
  (a) line, discrete time, t = 100: symmetric +-1 random walk (binomial law)
      against the Hadamard walk from the symmetric coin state (|0> + i|1>)/sqrt2,
      with the Konno weak-limit density overlaid.
  (b) line, continuous time, t = 50: continuous-time random walk with rate 1 per
      edge (p_x(t) = e^{-2t} I_x(2t)) against the continuous-time quantum walk
      generated by the adjacency matrix (psi_x(t) = (-i)^x J_x(2t)), with the
      arcsine weak-limit density overlaid.
  (c) standard deviation of the position against t for all four walks, and for
      the Hadamard walk with the coin measured (dephased) with probability q per
      step, q in {0.02, 0.1, 1}: the crossover from ballistic to diffusive spread.
  (d) cycle C_64, continuous time: the stationary distribution of the classical
      walk (uniform), the classical distribution at t = 400, the quantum
      distribution at t = 400, and the quantum time-averaged distribution
      (closed form: (2N-2)/N^2 at the start vertex and its antipode, (N-2)/N^2
      elsewhere).
"""
import json
import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))   # outputs are written next to this script
import numpy as np
from scipy.special import jv, iv
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

CLASSICAL = "#c0504d"
QUANTUM = "#1f5fa8"
LIMIT = "#444444"
plt.rcParams.update({"font.size": 8.5, "font.family": "serif", "axes.labelsize": 9,
                     "legend.fontsize": 7.5, "figure.dpi": 150})

out = {}

# ---------------------------------------------------------------- discrete time, line
T = 200
X = np.arange(-T, T + 1)


def classical_dt(T):
    P = np.zeros((T + 1, 2 * T + 1))
    P[0, T] = 1.0
    for t in range(1, T + 1):
        P[t, 1:] += 0.5 * P[t - 1, :-1]
        P[t, :-1] += 0.5 * P[t - 1, 1:]
    return P


def hadamard_dt(T, coin0=(1 / np.sqrt(2), 1j / np.sqrt(2))):
    """U = S (I x H): coin |0> moves right, |1> moves left. Returns p_t(x), t = 0..T."""
    psi = np.zeros((2, 2 * T + 1), dtype=complex)
    psi[0, T], psi[1, T] = coin0
    h = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
    P = np.zeros((T + 1, 2 * T + 1))
    P[0] = (np.abs(psi) ** 2).sum(0)
    for t in range(1, T + 1):
        c = h @ psi
        new = np.zeros_like(psi)
        new[0, 1:] = c[0, :-1]
        new[1, :-1] = c[1, 1:]
        psi = new
        P[t] = (np.abs(psi) ** 2).sum(0)
    return P


def decohered_hadamard(T, q):
    """Hadamard walk whose coin is measured (dephased in the computational basis)
    with probability q after every step. Density matrix on coin x position,
    kept as rho[c, x, c', x']. q = 1 is the classical walk exactly."""
    n = 2 * T + 1
    Xl = np.arange(-T, T + 1)
    v = np.zeros((2, n), dtype=complex)
    v[0, T], v[1, T] = 1 / np.sqrt(2), 1j / np.sqrt(2)
    rho = np.einsum("ax,by->axby", v, v.conj())
    h = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
    sd = np.zeros(T + 1)
    for t in range(1, T + 1):
        rho = np.einsum("ac,cxdy,bd->axby", h, rho, h.conj())
        new = np.zeros_like(rho)
        # shift: coin 0 -> x+1, coin 1 -> x-1, on both sides
        new[0, 1:, 0, 1:] = rho[0, :-1, 0, :-1]
        new[0, 1:, 1, :-1] = rho[0, :-1, 1, 1:]
        new[1, :-1, 0, 1:] = rho[1, 1:, 0, :-1]
        new[1, :-1, 1, :-1] = rho[1, 1:, 1, 1:]
        rho = new
        if q > 0:  # dephase the coin with probability q
            off = rho.copy()
            off[0, :, 0, :] = 0
            off[1, :, 1, :] = 0
            rho = rho - q * off
        p = np.real(np.einsum("axax->x", rho))
        sd[t] = np.sqrt((p * Xl ** 2).sum() - (p * Xl).sum() ** 2)
    return sd


Pc = classical_dt(T)
Ph = hadamard_dt(T)
sd_c = np.sqrt((Pc * X ** 2).sum(1))
sd_h = np.sqrt((Ph * X ** 2).sum(1) - (Ph * X).sum(1) ** 2)

# Konno's weak-limit density for the Hadamard walk (symmetric initial state):
# f(y) = 1 / (pi (1 - y^2) sqrt(1 - 2 y^2)),  |y| < 1/sqrt2,  y = x/t.
def konno(y):
    y = np.asarray(y, float)
    f = np.zeros_like(y)
    m = np.abs(y) < 1 / np.sqrt(2) - 1e-12
    f[m] = 1 / (np.pi * (1 - y[m] ** 2) * np.sqrt(1 - 2 * y[m] ** 2))
    return f


t0 = 100
out["dt"] = dict(t=t0, sd_classical=float(sd_c[t0]), sd_hadamard=float(sd_h[t0]),
                 sd_hadamard_over_t_T=float(sd_h[T] / T), konno_sd=float(np.sqrt(1 - 1 / np.sqrt(2))),
                 max_p_classical=float(Pc[t0].max()), max_p_hadamard=float(Ph[t0].max()),
                 argmax_hadamard=[int(X[i]) for i in np.flatnonzero(Ph[t0] == Ph[t0].max())],
                 p_origin_classical=float(Pc[t0, T]), p_origin_hadamard=float(Ph[t0, T]),
                 entropy_classical=float(-(Pc[t0][Pc[t0] > 0] * np.log2(Pc[t0][Pc[t0] > 0])).sum()),
                 entropy_hadamard=float(-(Ph[t0][Ph[t0] > 0] * np.log2(Ph[t0][Ph[t0] > 0])).sum()),
                 mass_inside_cone_hadamard=float(Ph[t0][np.abs(X) <= t0 / np.sqrt(2)].sum()),
                 mass_within_2sd_classical=float(Pc[t0][np.abs(X) <= 2 * np.sqrt(t0)].sum()))

# decoherence
DEC_T = 400
dec = {}
for q in (0.02, 0.1, 1.0):
    dec[q] = decohered_hadamard(DEC_T, q)
out["decoherence"] = {str(q): dict(sd_T=float(s[DEC_T]), sd_over_sqrtT=float(s[DEC_T] / np.sqrt(DEC_T)),
                                   sd_over_T=float(s[DEC_T] / DEC_T)) for q, s in dec.items()}
out["decoherence"]["classical_sd_T_over_sqrtT"] = 1.0

# ---------------------------------------------------------------- continuous time, line
tc = 50.0
XC = np.arange(-4 * int(tc) - 20, 4 * int(tc) + 21)
p_ct_classical = np.exp(-2 * tc) * iv(XC, 2 * tc)          # rate 1 per edge, generator -L
p_ct_quantum = jv(XC, 2 * tc) ** 2                          # H = A, psi_x = (-i)^x J_x(2t)
out["ct"] = dict(t=tc, norm_classical=float(p_ct_classical.sum()), norm_quantum=float(p_ct_quantum.sum()),
                 sd_classical=float(np.sqrt((p_ct_classical * XC ** 2).sum())),
                 sd_quantum=float(np.sqrt((p_ct_quantum * XC ** 2).sum())),
                 sd_classical_theory=float(np.sqrt(2 * tc)), sd_quantum_theory=float(np.sqrt(2) * tc),
                 p_origin_classical=float(p_ct_classical[XC == 0][0]), p_origin_quantum=float(p_ct_quantum[XC == 0][0]))


def arcsine(y):
    y = np.asarray(y, float)
    f = np.zeros_like(y)
    m = np.abs(y) < 2 - 1e-12
    f[m] = 1 / (np.pi * np.sqrt(4 - y[m] ** 2))
    return f


ts = np.linspace(0.5, 200, 400)
sd_ct_c = np.sqrt(2 * ts)
sd_ct_q = np.sqrt(2) * ts

# ---------------------------------------------------------------- cycle, continuous time
N = 64
k = np.arange(N)
lam = 2 * np.cos(2 * np.pi * k / N)
F = np.exp(-2j * np.pi * np.outer(k, k) / N) / np.sqrt(N)   # unitary DFT
tcyc = 400.0
psi = F.conj().T @ (np.exp(-1j * tcyc * lam) * F[:, 0])     # e^{-itA} |0>
p_cyc_q = np.abs(psi) ** 2
# classical: e^{-tL} with L = 2I - A on the cycle
p_cyc_c = np.real(F.conj().T @ (np.exp(-tcyc * (2 - lam)) * F[:, 0]))
# time average of the quantum walk: average over t of |<u| e^{-itA} |0>|^2, degenerate pairs (k, N-k) interfere
d = np.arange(N)
pbar = np.zeros(N)
for kk in range(N):
    for ll in range(N):
        if abs(lam[kk] - lam[ll]) < 1e-12:
            pbar += np.real(np.exp(2j * np.pi * (kk - ll) * d / N)) / N ** 2
pbar_closed = np.full(N, (N - 2) / N ** 2)
pbar_closed[0] = pbar_closed[N // 2] = (2 * N - 2) / N ** 2
out["cycle"] = dict(N=N, t=tcyc, max_dev_classical_from_uniform=float(np.abs(p_cyc_c - 1 / N).max()),
                    quantum_max=float(p_cyc_q.max()), quantum_min=float(p_cyc_q.min()),
                    tv_quantum_from_uniform=float(0.5 * np.abs(p_cyc_q - 1 / N).sum()),
                    timeavg_closed_form_error=float(np.abs(pbar - pbar_closed).max()),
                    timeavg_start=float(pbar[0]), timeavg_generic=float(pbar[1]),
                    tv_timeavg_from_uniform=float(0.5 * np.abs(pbar - 1 / N).sum()),
                    classical_gap=float(2 - 2 * np.cos(2 * np.pi / N)))

# ---------------------------------------------------------------- figure
fig, ax = plt.subplots(2, 2, figsize=(6.6, 5.4))
a = ax[0, 0]
m = (np.abs(X) <= t0) & ((X + t0) % 2 == 0)      # reachable sites only
a.plot(X[m], Pc[t0][m], color=CLASSICAL, lw=1.1, label="classical random walk")
a.plot(X[m], Ph[t0][m], color=QUANTUM, lw=0.9, label="Hadamard walk")
yy = np.linspace(-t0, t0, 2001)
a.plot(yy, 2 * konno(yy / t0) / t0, color=LIMIT, lw=0.8, ls="--", label="Konno limit density")
a.set_xlim(-t0, t0); a.set_ylim(0, 0.09)
a.set_xlabel("position $x$"); a.set_ylabel("$p_t(x)$")
a.set_title(f"(a) line, discrete time, $t={t0}$", loc="left", fontsize=8.5)
a.legend(frameon=False)

b = ax[0, 1]
mm = np.abs(XC) <= 2.6 * tc
b.plot(XC[mm], p_ct_classical[mm], color=CLASSICAL, lw=1.1, label="classical, rate 1 per edge")
b.plot(XC[mm], p_ct_quantum[mm], color=QUANTUM, lw=0.9, label="continuous-time quantum walk")
yy = np.linspace(-2.6 * tc, 2.6 * tc, 2001)
b.plot(yy, arcsine(yy / tc) / tc, color=LIMIT, lw=0.8, ls="--", label="arcsine limit density")
b.set_xlim(-2.6 * tc, 2.6 * tc); b.set_ylim(0, 0.045)
b.set_xlabel("position $x$"); b.set_ylabel("$p_t(x)$")
b.set_title(f"(b) line, continuous time, $t={tc:g}$", loc="left", fontsize=8.5)
b.legend(frameon=False)

c = ax[1, 0]
tt = np.arange(1, T + 1)
c.loglog(tt, sd_c[1:], color=CLASSICAL, lw=1.1, label="classical, discrete ($\\sqrt{t}$)")
c.loglog(tt, sd_h[1:], color=QUANTUM, lw=1.1, label="Hadamard walk ($0.54\\,t$)")
c.loglog(ts, sd_ct_c, color=CLASSICAL, lw=1.1, ls=":", label="classical, continuous ($\\sqrt{2t}$)")
c.loglog(ts, sd_ct_q, color=QUANTUM, lw=1.1, ls=":", label="continuous-time quantum ($\\sqrt{2}\\,t$)")
for q, ls in zip((0.02, 0.1, 1.0), ("-.", "--", (0, (1, 1)))):
    c.loglog(np.arange(1, DEC_T + 1), dec[q][1:], color="#6a9c3a", lw=0.9, ls=ls, label=f"Hadamard, coin measured, $q={q:g}$")
c.set_xlabel("time $t$"); c.set_ylabel("standard deviation of position")
c.set_title("(c) spread against time", loc="left", fontsize=8.5)
c.legend(frameon=False, ncol=1, fontsize=6.3, loc="upper left")

dd = ax[1, 1]
dd.plot(d, p_cyc_c, color=CLASSICAL, lw=1.1, label=f"classical, $t={tcyc:g}$ (stationary)")
dd.plot(d, p_cyc_q, color=QUANTUM, lw=0.8, label=f"quantum, $t={tcyc:g}$")
dd.plot(d, pbar, color=QUANTUM, lw=1.1, ls="--", label="quantum, time average")
dd.axhline(1 / N, color=LIMIT, lw=0.7, ls=":")
dd.set_xlabel("vertex $u$ (start at 0)"); dd.set_ylabel("$p(u)$")
dd.set_xlim(0, N - 1)
dd.set_title(f"(d) cycle $C_{{{N}}}$, continuous time", loc="left", fontsize=8.5)
dd.legend(frameon=False)

fig.tight_layout()
fig.savefig("fig_walk_crw.pdf")
fig.savefig("fig_walk_crw.png", dpi=200)

# ---------------------------------------------------------------- table
rows = [
    ("Classical walk, discrete time", "Gaussian in $x/\\sqrt{t}$", "$\\sqrt{t}$",
     out["dt"]["sd_classical"], out["dt"]["p_origin_classical"], out["dt"]["entropy_classical"]),
    ("Hadamard walk, symmetric coin", "Konno, $|x/t|<1/\\sqrt{2}$", "$0.541\\,t$",
     out["dt"]["sd_hadamard"], out["dt"]["p_origin_hadamard"], out["dt"]["entropy_hadamard"]),
]
# continuous-time rows at t = 100 for the same table
tq = 100.0
XQ = np.arange(-400, 401)
pcc = np.exp(-2 * tq) * iv(XQ, 2 * tq); pqq = jv(XQ, 2 * tq) ** 2
rows += [
    ("Classical walk, continuous time", "Gaussian in $x/\\sqrt{t}$", "$\\sqrt{2t}$",
     float(np.sqrt((pcc * XQ ** 2).sum())), float(pcc[XQ == 0][0]), float(-(pcc[pcc > 0] * np.log2(pcc[pcc > 0])).sum())),
    ("Continuous-time quantum walk", "arcsine, $|x/t|<2$", "$\\sqrt{2}\\,t$",
     float(np.sqrt((pqq * XQ ** 2).sum())), float(pqq[XQ == 0][0]), float(-(pqq[pqq > 0] * np.log2(pqq[pqq > 0])).sum())),
]
out["table_t"] = tq
with open("tab_walk_crw.tex", "w") as f:
    f.write("\\begin{table}[htbp]\n\\centering\\small\n")
    f.write("\\caption[Classical and quantum walks on the line at $t=100$]{Classical and quantum walks on the line "
            "from the origin: the limiting law (of $x/\\sqrt{t}$ for the classical walks, of $x/t$ for the quantum walks), the standard "
            "deviation of the position as a function of $t$, and its value, the probability of being at the origin "
            "and the Shannon entropy of the position distribution at $t=100$. The classical continuous-time walk "
            "has rate $1$ per edge and the quantum one is generated by the adjacency matrix. All values are exact.}\n")
    f.write("\\label{tab:walkcrw}\n\\begin{tabular}{llrrrr}\n\\hline\n")
    f.write("Walk & Limit law & $\\sigma(t)$ & $\\sigma(100)$ & $p_{100}(0)$ & $H$ (bits) \\\\\n\\hline\n")
    for name, law, sig, s, p0, H in rows:
        f.write(f"{name} & {law} & {sig} & ${s:.1f}$ & ${p0:.4f}$ & ${H:.2f}$ \\\\\n")
    f.write("\\hline\n\\end{tabular}\n\\end{table}\n")

json.dump(out, open("walk_vs_crw.json", "w"), indent=1)
print(json.dumps(out, indent=1))
