"""
Thesis figure for the circuit-scaling result.

One question: how does the cost of a walk step grow with the number of
vertices, and does the construction change the answer?  That is
change-over-a-scale, so a log-log line chart, with the two constructions
separated by colour and the graph families by line style.  The per-vertex
coin is a third colour because it is a different claim -- not a cheaper way
to build the same thing, but the term that survives the improvement.

Every line is directly labelled at its right-hand end, so the series are
identifiable without the legend and in greyscale.
"""

import json

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

SURFACE = "#ffffff"
INK = "#0b0b0b"
INK_2 = "#52514e"
GRID = "#e3e2dd"
DENSE = "#eb6834"
STRUCT = "#2a78d6"
COIN = "#1baf7a"

plt.rcParams.update({
    "font.family": "sans-serif", "font.size": 8.5,
    "axes.edgecolor": GRID, "axes.labelcolor": INK_2,
    "xtick.color": INK_2, "ytick.color": INK_2,
    "figure.facecolor": SURFACE, "axes.facecolor": SURFACE,
    "savefig.facecolor": SURFACE,
})

rows = json.load(open("scaling_structured.json"))
coin = json.load(open("coin_cost.json"))

STYLE = {"cycle": "-", "torus": "--", "hypercube": ":"}
MARK = {"cycle": "o", "torus": "s", "hypercube": "^"}

fig, ax = plt.subplots(figsize=(7.2, 4.3))

for fam in ("cycle", "torus", "hypercube"):
    fr = sorted([r for r in rows if r["family"] == fam], key=lambda r: r["N"])
    nd = [(r["N"], r["dense_cx"]) for r in fr if r["dense_cx"]]
    ns = [(r["N"], r["str_cx"]) for r in fr if r["str_cx"]]
    if nd:
        ax.plot(*zip(*nd), color=DENSE, linestyle=STYLE[fam], marker=MARK[fam],
                markersize=3.5, linewidth=1.5, zorder=3)
    ax.plot(*zip(*ns), color=STRUCT, linestyle=STYLE[fam], marker=MARK[fam],
            markersize=3.5, linewidth=1.5, zorder=3)

# split by family: two points can share an N (C16 and T4x4 both have 16
# vertices), and joining them would draw a vertical jump that is a family
# difference, not a scaling effect
for fam, style in (("C", "-"), ("T", "--")):
    cn = sorted([(r["N"], r["cx_pv"]) for r in coin if r["name"].startswith(fam)])
    ax.plot(*zip(*cn), color=COIN, linestyle=style, marker="D", markersize=3.5,
            linewidth=1.5, zorder=3)

ax.set_xscale("log", base=2)
ax.set_yscale("log")
ax.set_xlabel("vertices $N$")
ax.set_ylabel("two-qubit (CX) gates per walk step, after transpilation")
ax.grid(color=GRID, linewidth=0.6, which="major", zorder=0)
ax.grid(color=GRID, linewidth=0.3, which="minor", zorder=0)
ax.set_axisbelow(True)
for side in ("top", "right"):
    ax.spines[side].set_visible(False)
ax.set_xlim(3, 3000)
ax.set_ylim(1, 5e5)

ax.annotate("dense synthesis\n$\\sim N^{2}$", xy=(256, 119383),
            xytext=(300, 190000), color=DENSE, fontsize=8,
            ha="left", va="center")
ax.annotate("structured shift\npolylog $N$", xy=(1024, 1614),
            xytext=(120, 4200), color=STRUCT, fontsize=8,
            ha="left", va="center")
ax.annotate("per-vertex coin\n(axis 1)", xy=(32, 132515),
            xytext=(4.2, 60000), color=COIN, fontsize=8,
            ha="left", va="center")

handles = [
    plt.Line2D([], [], color=DENSE, linewidth=1.8, label="dense synthesis"),
    plt.Line2D([], [], color=STRUCT, linewidth=1.8, label="structured shift, uniform coin"),
    plt.Line2D([], [], color=COIN, linewidth=1.8, label="structured shift, per-vertex coin"),
    plt.Line2D([], [], color=INK_2, linewidth=1.2, linestyle="-", marker="o",
               markersize=3.5, label="cycle"),
    plt.Line2D([], [], color=INK_2, linewidth=1.2, linestyle="--", marker="s",
               markersize=3.5, label="torus"),
    plt.Line2D([], [], color=INK_2, linewidth=1.2, linestyle=":", marker="^",
               markersize=3.5, label="hypercube"),
]
ax.legend(handles=handles, loc="lower right", frameon=False, fontsize=7.3,
          ncol=2, columnspacing=1.2)

fig.tight_layout()
fig.savefig("fig_walk_scaling.pdf", bbox_inches="tight")
fig.savefig("fig_walk_scaling.png", dpi=200, bbox_inches="tight")
print("wrote fig_walk_scaling.pdf / .png")

# ------------------------------------------------------- LaTeX table -----

with open("tab_scaling.tex", "w") as f:
    f.write("% Generated by plot_scaling.py -- do not edit by hand.\n")
    f.write("\\begin{table}[htbp]\n\\centering\n")
    f.write("\\caption{Two-qubit gate count for one walk step after "
            "transpilation to $\\{\\mathrm{CX}, R_Z, \\sqrt{X}, X\\}$ at "
            "optimisation level~3. Dashes mark instances whose dense "
            "operator was not built.}\n\\label{tab:scaling}\n")
    f.write("\\begin{tabular}{llrrrr}\n\\hline\n")
    f.write("Family & Graph & $N$ & Qubits & Dense CX & Structured CX \\\\\n")
    f.write("\\hline\n")
    for fam in ("cycle", "torus", "hypercube"):
        for r in sorted([x for x in rows if x["family"] == fam],
                        key=lambda x: x["N"]):
            dc = f"{r['dense_cx']}" if r["dense_cx"] else "---"
            f.write(f"{fam} & {r['name']} & {r['N']} & {r['qubits']} & "
                    f"{dc} & {r['str_cx']} \\\\\n")
        f.write("\\hline\n")
    f.write("\\end{tabular}\n\\end{table}\n")
print("wrote tab_scaling.tex")
