"""Figure and table of thesis Section 3.6.3 from qaoa_results.json (written by qaoa_walk.py); nothing is computed here."""
import json, os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

os.chdir(os.path.dirname(os.path.abspath(__file__)))
INK, INK_2, GRID = "#0b0b0b", "#52514e", "#e3e2dd"
BLUE, ORANGE, NEUTRAL = "#2a78d6", "#eb6834", "#8a8985"
plt.rcParams.update({"font.family": "sans-serif", "font.size": 8.5, "axes.edgecolor": GRID, "axes.labelcolor": INK_2,
                     "xtick.color": INK_2, "ytick.color": INK_2})


def save(fig, name):
    fig.savefig(name + ".pdf", bbox_inches="tight")
    fig.savefig(name + ".png", dpi=200, bbox_inches="tight")
    plt.close(fig)


Q = json.load(open("qaoa_results.json"))
ps = sorted(int(p) for p in Q[0]["results"])
fig, ax = plt.subplots(figsize=(7.2, 3.2))
names = [("CTQW-J", BLUE, "CTQW mixer on $J(8,4)$"), ("DTQW-J", ORANGE, "DTQW mixer on $J(8,4)$ (one step/layer)"),
         ("X", NEUTRAL, "$X$ mixer + penalty")]
w = 0.26
for i, (key, col, lab) in enumerate(names):
    mu = [np.mean([r["results"][str(p)][key]["ratio"] for r in Q]) for p in ps]
    sd = [np.std([r["results"][str(p)][key]["ratio"] for r in Q]) for p in ps]
    x = np.array(ps) + (i - 1) * w
    ax.bar(x, mu, width=w - 0.03, color=col, zorder=3, label=lab)
    ax.errorbar(x, mu, yerr=sd, fmt="none", ecolor=INK_2, elinewidth=0.9, capsize=2, zorder=4)
    for xi, m_, s_ in zip(x, mu, sd):
        ax.text(xi, m_ + s_ + 0.015, f"{m_:.2f}", ha="center", va="bottom", fontsize=6.5, color=INK)
base = np.mean([r["ratio_uniform_feasible"] for r in Q])
ax.axhline(base, color=INK, linewidth=0.9, linestyle=":", zorder=2)
ax.text(ps[0] - 0.45, base + 0.012, "uniform feasible", ha="left", va="bottom", fontsize=7, color=INK, style="italic")
ax.set_xticks(ps); ax.set_xlabel("QAOA depth $p$")
ax.set_ylabel(r"$\mathbb{E}[C(x)\,\mathbb{1}_{\mathrm{feasible}}]/C_{\mathrm{opt}}$")
ax.set_ylim(0, 1.05)
ax.legend(frameon=False, fontsize=7, loc="upper left", ncol=3)
ax.grid(axis="y", color=GRID, linewidth=0.6, zorder=0)
save(fig, "fig_qaoa_mixers")

with open("tab_qaoa.tex", "w") as f:
    f.write("% Generated by report_qaoa.py -- do not edit by hand.\n")
    f.write("\\begin{table}[htbp]\n\\centering\\small\n")
    f.write("\\caption[Balanced maximum cut: walk mixers against the penalised $X$ mixer]{Balanced Max-Cut on six random weighted graphs ($n=8$, $|S|=4$): approximation ratio "
            "$\\mathbb{E}[C(x)\\mathbf{1}_{\\mathrm{feasible}}]/C_{\\mathrm{opt}}$ and probability of a feasible "
            "outcome, mean $\\pm$ s.d.\\ over instances, best of twelve COBYLA starts. A uniform draw from the "
            f"feasible set scores {base:.2f}.}}\n")
    f.write("\\label{tab:qaoa}\n\\begin{tabular}{clrr}\n\\hline\n")
    f.write("$p$ & Mixer & Ratio & $P(\\mathrm{feasible})$ \\\\\n\\hline\n")
    for p in ps:
        for key, _, lab in names:
            rr = [r["results"][str(p)][key]["ratio"] for r in Q]
            pf = [r["results"][str(p)][key]["p_feasible"] for r in Q]
            f.write(f"{p if key == 'CTQW-J' else ''} & {lab} & ${np.mean(rr):.3f} \\pm {np.std(rr):.3f}$ & "
                    f"${np.mean(pf):.2f} \\pm {np.std(pf):.2f}$ \\\\\n")
        f.write("\\hline\n")
    f.write("\\end{tabular}\n\\end{table}\n")

