"""Figure and tables for the walk-DLP LAT pipeline. Reads dlp_scan.json and pipeline_walk_dlp.json."""
import json, collections
import numpy as np
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.stats import binomtest

scan = json.load(open("dlp_scan.json"))
R = json.load(open("pipeline_walk_dlp.json"))
SIZES = [8, 10, 12, 16]

# ---- best m per (n, kind) and the DT/CT cost comparison -------------------------------------------------------
best = {}
for d in scan:
    if d["expected_calls"] is None:
        continue
    k = (d["n"], d["kind"])
    if k not in best or d["expected_calls"] < best[k]["expected_calls"]:
        best[k] = d
L = [r"\begin{table}[htbp]", r"\centering", r"\small",
     r"\caption[Walk formulations of the discrete-logarithm step]{The discrete-logarithm step as phase estimation on a "
     r"walk over $\mathbb{Z}_p^*$: the discrete-time permutation walk $U_g$, $U_x$ and the continuous-time walk generated by "
     r"$H = U + U^\dagger$. For each bit length $n$, the counting-register size $m$ that minimises the expected number of "
     r"oracle calls (controlled modular multiplications, or unit walk time) per verified logarithm, the per-attempt success "
     r"probability at that $m$, and the expected calls. Estimated from $25$ exponents and $200$ attempts each.}",
     r"\label{tab:dlpwalk}", r"\begin{tabular}{lrrrrrr}", r"\hline",
     r"$n$ & \multicolumn{3}{c}{discrete-time walk} & \multicolumn{3}{c}{continuous-time walk} \\",
     r" & $m$ & success & calls & $m$ & success & calls \\", r"\hline"]
for n in SIZES:
    a, b = best[(n, "DT")], best[(n, "CT")]
    L.append(f"{n} & {a['m']} & ${a['success']:.2f}$ & ${a['expected_calls']:.0f}$ & {b['m']} & ${b['success']:.2f}$ & "
             f"${b['expected_calls']:.3g}$ \\\\".replace("e+0", r"\times 10^{").replace("e+", r"\times 10^{"))
L += [r"\hline", r"\end{tabular}", r"\end{table}", ""]
txt = "\n".join(L)
# tidy scientific notation produced above
import re
txt = re.sub(r"\$(\d\.\d+)\\times 10\^\{(\d+)\$", r"$\1 \\times 10^{\2}$", txt)
open("tab_dlp_walk.tex", "w").write(txt)

# ---- accuracy against budget -------------------------------------------------------------------------------
agg = collections.defaultdict(list)
for v in R.values():
    agg[(v["kind"], v["n"], str(v["budget"]))].append(v)
BUD = ["1", "2", "4", "8", "16", "inf"]
rows = []
for kind in ["DT", "CT"]:
    for n in SIZES:
        for K in BUD:
            Lr = agg[(kind, n, K)]
            if not Lr:
                continue
            rows.append(dict(kind=kind, n=n, K=K, exact=np.mean([x["frac_exact"] for x in Lr]),
                             calls=np.mean([x["mean_calls"] for x in Lr]),
                             qnn=np.mean([x["CTQW-QNN"]["test_acc"] for x in Lr]), lat=np.mean([x["LAT kernel"]["test_acc"] for x in Lr]),
                             qnn_sd=np.std([x["CTQW-QNN"]["test_acc"] for x in Lr], ddof=1) if len(Lr) > 1 else 0,
                             lat_sd=np.std([x["LAT kernel"]["test_acc"] for x in Lr], ddof=1) if len(Lr) > 1 else 0))
ident = [(v["CTQW-QNN"].get("identical_to_lookup_table"), v["LAT kernel"].get("identical_to_lookup_table"))
         for v in R.values() if v["budget"] == "inf"]
print("K=inf identical to lookup-table run:", sum(a and b for a, b in ident), "/", len(ident))

# table: DT walk, accuracy vs attempt budget
L = [r"\begin{table}[htbp]", r"\centering", r"\small", r"\setlength{\tabcolsep}{4pt}",
     r"\caption[Discrete-logarithm task with the walk DLP step: accuracy against budget]{The LAT pipeline with the "
     r"discrete-time walk in place of the lookup table. For an attempt budget $K$ an input receives its verified logarithm "
     r"if one of its first $K$ phase-estimation attempts succeeds, and a uniformly random exponent otherwise; "
     r"$K = \infty$ repeats until verified. Fraction of inputs with the exact logarithm, mean oracle calls per input, "
     r"and test accuracy (\%) of the walk QNN and of the LAT kernel, means over five draws.}",
     r"\label{tab:dlpbudget}", r"\begin{tabular}{rrrrrr}", r"\hline",
     r"$n$ & $K$ & exact & calls & walk QNN & LAT kernel \\", r"\hline"]
for n in SIZES:
    for K in BUD:
        r_ = [x for x in rows if x["kind"] == "DT" and x["n"] == n and x["K"] == K][0]
        Kl = r"$\infty$" if K == "inf" else K
        L.append(f"{n} & {Kl} & ${r_['exact']:.2f}$ & ${r_['calls']:.0f}$ & ${100 * r_['qnn']:.1f}$ & ${100 * r_['lat']:.1f}$ \\\\")
    if n != SIZES[-1]:
        L.append(r"\hline")
L += [r"\hline", r"\end{tabular}", r"\end{table}", ""]
open("tab_dlp_budget.tex", "w").write("\n".join(L))

# figure: accuracy vs oracle calls per input, DT (solid) and CT (dashed), one panel per n
fig, axes = plt.subplots(1, 4, figsize=(9.6, 2.9), dpi=150, sharey=True)
for ax, n in zip(axes, SIZES):
    for kind, ls in (("DT", "-"), ("CT", "--")):
        r_ = [x for x in rows if x["kind"] == kind and x["n"] == n]
        ax.plot([x["calls"] for x in r_], [x["qnn"] for x in r_], color="#2a78d6", ls=ls, marker="o", ms=4, lw=1.8,
                label=f"walk QNN, {'discrete' if kind == 'DT' else 'continuous'}-time DLP")
        ax.plot([x["calls"] for x in r_], [x["lat"] for x in r_], color="#eb6834", ls=ls, marker="s", ms=4, lw=1.8,
                label=f"LAT kernel, {'discrete' if kind == 'DT' else 'continuous'}-time DLP")
    ax.set_xscale("log"); ax.set_title(f"$n = {n}$", fontsize=10); ax.set_xlabel("oracle calls per input")
    ax.axhline(0.5, color="#8c8c86", lw=1, ls=":"); ax.set_ylim(0.4, 1.02)
    ax.grid(axis="y", color="#e6e5df", lw=0.8); ax.set_axisbelow(True)
    for sp in ["top", "right"]:
        ax.spines[sp].set_visible(False)
axes[0].set_ylabel("test accuracy")
axes[0].legend(frameon=False, fontsize=6.5, loc="lower right")
fig.tight_layout()
fig.savefig("fig_dlp_budget.pdf"); fig.savefig("fig_dlp_budget.png")

# pooled McNemar QNN vs LAT at each budget (DT), over draws and sizes
for K in BUD:
    x = y = 0
    for v in R.values():
        if v["kind"] == "DT" and str(v["budget"]) == K:
            ca = np.array(v["CTQW-QNN"]["correct"]); cb = np.array(v["LAT kernel"]["correct"])
            x += int(((ca == 1) & (cb == 0)).sum()); y += int(((ca == 0) & (cb == 1)).sum())
    print(f"DT K={K}: QNN-only {x}, LAT-only {y}, p={binomtest(x, x + y, 0.5).pvalue if x + y else 1:.3g}")
json.dump(rows, open("pipeline_summary.json", "w"), indent=1, default=float)
